.circleci/config.yml, frontend/Dockerfile, frontend/package-lock.json, frontend/package.json, frontend/test.sh
Configure support for greenkeeper-lockfile.
This will resolve #25.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/25)
=> integrate greenkeeper

README.md, codecov.yml, frontend/.babelrc, frontend/.gitignore, frontend/package-lock.json, frontend/package.json, frontend/src/api/Util/__tests__/Response.js, frontend/test.sh
This resolves #29.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/30)
=> Frontend: add testing boilerplate; integrate codecov

.circleci/config.yml
This should resolve #31.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/32)
=> [BUGFIX] push built images to docker hub on master branch

backend/app/model/models/Dimension.py, backend/app/model/models/Question.py, backend/app/model/models/Questionnaire.py, backend/app/model/models/SurveyBase.py
This will resolve #6 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/34)
=> [BUGFIX] generate SurveyBase.reference_id explicitly on creation

backend/app/api/schema/Questionnaire.py
This will resolve Issue #20 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/35)
=> [BUGFIX] add password challenge information to Questionnaire schema

backend/app/framework/xapi/submission_hooks/__init__.py
This resolves #11 and also prevents another potential bug related to the same piece of code, where submission hooks would cause the submission to fail when no reference_id is set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/37)
=> [BUGFIX] Fix (standalone) submission hook 

frontend/src/Plugins/LoadingSpinnerModal/LoadingSpinnerModal.vue, frontend/src/components/App.vue, frontend/src/components/Partials/Modal/ClosableModal.vue, frontend/src/components/Partials/Modal/CreateDimension.vue, frontend/src/components/Partials/Modal/CreateQuestion.vue, frontend/src/components/Partials/Modal/CreateQuestionnaire.vue, frontend/src/components/Partials/Modal/CreateResource.vue, frontend/src/components/Partials/Modal/Dialog.vue, frontend/src/components/Partials/Modal/TranslateDimension.vue, frontend/src/components/Partials/Modal/TranslateQuestion.vue, frontend/src/components/Partials/Modal/TranslateQuestionnaire.vue, frontend/src/components/Partials/Modal/TranslateResource.vue, frontend/src/components/Partials/Modal/UseDimensionTemplate.vue, frontend/src/components/Partials/Modal/UseQuestionTemplate.vue, frontend/src/components/Partials/Modal/UseQuestionnaireTemplate.vue, nginx/nginx.conf
made structural changes necessary
Will resolve #14.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/41)
=> [BUGFIX] close modal on session changes

.circleci/config.yml
This will resolve #31.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/38)
=> [BUGFIX] fix check for master branch in circleci config

frontend/src/components/Partials/Modal/UseDimensionTemplate.vue, frontend/src/components/Partials/Modal/UseQuestionTemplate.vue, frontend/src/components/Views/Embedded/EmbeddedSurveyForSubmission.vue, frontend/src/components/Views/Public/SurveyForSubmission.vue, frontend/src/components/scss/_variables.scss
It will look better. I've got the greatest designs, believe me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/46)
=> Style adjustements

backend/app/framework/xapi/submission_hooks/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/50)
=> backend: fix wrong usage of getattr in submission_hooks

xapi-publisher/app/main.py
This resolves #45 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/60)
=> [BUGFIX] xapi-publisher: accept all 2xx status codes as success

frontend/src/components/Partials/SurveyBase/Submission/QuestionForm.vue, frontend/src/components/Views/Public/SurveyForSubmission.vue
User specific errors will no display an error message in the footer instead of as a notification.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/57)
=> [FEATURE] Error message field in standalone survey

frontend/src/components/Views/Public/SurveyForSubmission.vue
This resolves #55 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/58)
=> [FEATURE] Pagination buttons for standalone survey

frontend/src/components/App.vue, frontend/src/components/Partials/Modal/UpdateAllRangeLabels.vue, frontend/src/components/Partials/SurveyBase/Dimension.vue, frontend/src/components/scss/_variables.scss, frontend/src/utility/functional.js
This resolves #54 .
There's a button in `Dimension.vue` now, which will show a modal for the feature. The modal will also display warnings if:
1) The Questions in the Dimension use different ranges
2) There are ShadowQuestions present in the Dimension
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/63)
=> [FEATURE] update all range labels for dimension at once in frontend

backend/app/api/DataSubject.py, backend/app/api/schema/DataSubject.py, backend/app/api/schema/Submission.py, backend/app/main.py, backend/app/model/models/QuestionResponse.py, frontend/src/api/DataSubject.js, frontend/src/api/Util/Parse.js, frontend/src/components/App.vue, frontend/src/components/Partials/Modal/ForgetDataSubject.vue, frontend/src/components/Views/Private/Account.vue, frontend/src/model/DataSubject.js
This adds a modal to the Account view, where an Admin user may delete all personal data for a given DataSubject. This will resolve #44 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/49)
=> [FEATURE] Forget datasubject

frontend/src/components/Views/Public/SurveyForSubmission.vue
This will resolve #19 .
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/56)
=> [FEATURE] Thank you page after standalone submisison

frontend/src/components/Views/Embedded/Partials/WelcomePage.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/68)
=> [FEATURE] minor style changes in embedded WelcomePage

backend/app/api/DataClient.py, frontend/src/components/Views/Public/Authentication.vue
This is a requirement for my bachelor's thesis.
This removes the registration form from the frontend and makes the API require admin privileges to create a new user.
First time user creation should now be done via cli.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/59)
=> [FEATURE] Disable registration

backend.env, backend/app/app.py, backend/app/cli.py, backend/app/flask.cfg, backend/app/framework/config.py, backend/app/framework/flask.py, backend/app/framework/xapi/signals.py, backend/app/main.py, backend/app/model/__init__.py, backend/app/model/models/DataSubject.py, backend/app/model/models/Questionnaire.py, docker-compose.yml
Also cleaned up config by removing unused config keys.
This resolves #78 .
This is needed to configure SMTP credentials after building without committing them to git.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/79)
=> [FEATURE] backend: read config items from docker-compose env_files

backend/app/api/Questionnaire.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/84)
=> [BUGFIX] Make ShadowQuestionnaire.accepts_submissions updatable

backend/app/api/Response.py, backend/app/framework/email.py, backend/app/model/models/Question.py, backend/app/model/models/QuestionResponse.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/83)
=> [BUGFIX] backend: various fixes in submission & verification logic

frontend/src/components/Partials/SurveyBase/Submission/DimensionForm.vue
This resolves #82 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/85)
=> [BUGFIX] sort DimensionForm by Question.position

frontend/src/components/Views/Embedded/EmbeddedSurveyForSubmission.vue, frontend/src/components/Views/Public/SurveyForSubmission.vue
This resolves #86 . It also replaces the pagination buttons' text with svg icons of arrows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/89)
=> [FEATURE] better pagination buttons for submission frontend

backend/app/api/Response.py
This resolves #87 . It also introduces descriptive error messages to the submission endpoint, when sending of the verification email fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/88)
=> [BUGFIX] descriptive api errors in submission

xapi-publisher/app/main.py
The publisher now also retries sending for RequestException. This exception happens in case of network or protocol errors. It's also now using a status check after task completion instead of manually checking the
retry count, as this would fail in some cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/94)
=> [BUGFIX] xapi-publisher: improved error handling

backend/app/api/Session.py
This resolves #90.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/93)
=> [BUGFIX] backend: check if LTI launch locale was specified 

frontend/src/components/Views/Embedded/EmbeddedSurveyForSubmission.vue
Just some minor css stuff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/98)
=> [BUGFIX] broken buttons in embedded front end

frontend/src/api/Util/Response.js, frontend/src/api/Util/__tests__/Response.js, frontend/src/api/Util/renameProp.js, frontend/src/express/embeddedAuthenticationMiddleware.js
Adds a suit of unit tests for Response.js checking json extraction and Response categorization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/99)
=> [TASK] Add Tests for Response.js

frontend/src/api/Errors/index.js, frontend/src/api/Util/Parse.js, frontend/src/api/Util/__tests__/Parse.js, frontend/src/api/Util/__tests__/__snapshots__/Parse.js.snap
This adds some tests for parser functions.
I will update this pull request as I add more tests.
Feel free to review; If you do I will merge whatever is accepted and open a new PR for the next tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/100)
=> [TASK] add unit-tests for parser functions

backend/app/app.py, backend/app/framework/logging.py, backend/app/main.py, backend/app/model/models/DataClient.py, backend/app/model/models/DataSubject.py
The log statement was previously missing. This also improves the log formatting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yeldirium/st3k101/101)
=> [BUGFIX] log application errors
